### ISSUE TITLE
release a new version

### ISSUE THREAD

**Issue by jerome-laforge** [go-kit/log#12]
Is it plan to release anew version in order to have the latest version of github.com/go-logfmt/logfmt with go-kit/kit?

**Comment by ChrisHines** [comment]
Yes, that was the plan and it was completed today with the release of github.com/go-kit/kit v0.12.0.

Specifically:

[github.com/go-kit/kit v0.12.0](https://github.com/go-kit/kit/releases/tag/v0.12.0) released today requires [github.com/go-kit/log v0.2.0](https://github.com/go-kit/log/releases/tag/v0.2.0) released last week, which requires [github.com/go-logfmt/logfmt v0.5.1](https://github.com/go-logfmt/logfmt/releases/tag/v0.5.1) released 2021-aug-18.

**Comment by jerome-laforge** [comment]
Thanks
