### ISSUE TITLE
consider providing a method to compute the log level based on a String

### ISSUE THREAD

**Issue by carocad** [go-kit/log#18]
For most of our apps we setup the log level based on environment variables. However go-kit/log currently has hardcoded internal levels which makes mapping from the env var setting to the real level more cumbersome.

I checked the code since you already have a Value interface for the log levels which should be usable through [this function](https://github.com/go-kit/log/blob/main/level/level.go#L129), unfortunately it seems unused as [here](https://github.com/go-kit/log/blob/main/level/level.go#L51) it is casted to levelValue instead of Value.

Hope it helps

**Comment by alex-eftimie** [comment]
Right now there doesn't seem to be any other way to set the log level excep for using the pattern
`func Allow...`
If one were to set the level through any sort of application code is there any way currently to avoid a verbose switch with all the levels?

**Comment by ChrisHines** [comment]
>... is there any way currently to avoid a verbose switch with all the levels?

Not with the code in this package, no. But I think the details of that switch statement depend on details of the application that are out of scope for this package.

If you have many applications within a project that you want to use that switch statement in, that's a good candidate for a project library to encode that behavior in a single place.

I don't think it's a hard switch statement to write. You could probably also define a `map[string]level.Option` to lookup which option to use.

**Comment by alex-eftimie** [comment]
The project library is essentially what I ended up doing

**Comment by peterbourgon** [comment]
For the record, I also end up doing something like this, once a project reaches a certain size. But few of my projects get there.
