### ISSUE TITLE
Leveled Logger: Get current log-level from logger

### ISSUE THREAD

**Issue by mrueg** [go-kit/log#27]
I'm using the leveled logger and would like to check the log level of the logger instance. Given an instance, is there any way to get the current log level it is set to?

Context: I want to see which level is used before running a specific compute action that can be omitted if the logger is not on a debug level.

**Comment by peterbourgon** [comment]
tl;dr: no

There isn't really a concept of "the log level of a logger instance" in the current architecture. Levels are just specific keyvals that receive special treatment by level.Filter, and are usually added by decorators like log.Debug. If you want introspection, you should probably write your own version of level.Filter which maintains state and can be queried.
