### ISSUE TITLE
OpenTelemetry Integration

### ISSUE THREAD

**Issue by hbjydev** [go-kit/log#37]
Hi all. I'm looking at potentially trying to patch this package to have an OpenTelemetry wrapper around it that would allow you to ship logs using the (albeit experimental currently) OpenTelemetry Logs API to an OTel collector.

Currently, the challenge I have that is preventing me from being able to build this as a separate package is that I can't intercept the K/V data from log lines because the log context type is private, as are all its fields.

I was wondering if this would be a series of changes that you guys would be interested in upstreaming (which I'd maintain, obviously, not looking to generate undue work for anyone), or if this is more of a "maintain your own fork" situation due to the nature of what I'd be trying to add?

Thanks!

**Comment by ChrisHines** [comment]
Can you provide more details about what you need to do with the non-exported types? Maybe there is a way to do what you need that isn't obvious.

**Comment by hbjydev** [comment]
Primarily, I need to get the data to satisfy this struct: https://github.com/open-telemetry/opentelemetry-go/blob/main/log/record.go

So I need to be able to read the Key/Value data on the logger prior to and during `.Log(...)` calls, so I can then call `record.AddAttribute(key, value)`.

**Comment by hbjydev** [comment]
Ideally, I'd be operating on the data here: https://github.com/go-kit/log/blob/main/log.go#L133

**Comment by ChrisHines** [comment]
Typically that is done by implementing the `log.Logger` interface as a decorator for the "real" logger and inspecting the keyvals before passing them on the wrapped logger.

**Comment by hbjydev** [comment]
Do you have a psuedocode example of how to do that? Or does `log.With(...)` make it so that the end `.Log()` call gets all the key-value pairs anyway?

**Comment by ChrisHines** [comment]
Yes, the `Log` method of the logger returned by `log.With` resolves and passes all the key-value pairs down to the logger given to the `log.With` call.

The tests in https://github.com/go-kit/log/blob/main/value_test.go show how this works and verify it works as desired.

**Comment by hbjydev** [comment]
Cool, thank you! I'll see if I can get it all working with that then :)

Appreciate the help, both.
