### ISSUE TITLE
Enhancement: Standardize go-kit/log to OpenTelemetry format

### ISSUE THREAD

**Issue by khushijain21** [go-kit/log#40]
A standard format for logs as defined by [OTel specifications](https://opentelemetry.io/docs/specs/otel/logs) will help end-users unify logging and correlate it with different observability signals.

Proposal1: To Provide a logging bridge between go-kit/log and OpenTelemtry. Draft PR for the same - https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5932

Proposal2: Align existing encoders (logfmt, json) to emit logs in OTel format.

If the community finds this helpful, I can contribute here. Also please do share if there are any better approaches for the same.

**Comment by peterbourgon** [comment]
Feel free to implement this idea in a separate repo, I'm happy to link to it in the e.g. README
